spring:
  datasource:
    username: sa
    password: 123
    url: jdbc:h2:mem:CrudShop
    driver-class-name: org.h2.Driver

  jpa:
    hibernate: create
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false
  h2:
    console:
      enabled: true