server:
  servlet:
    context-path: /my-app
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CrudShop
    username: postgres
    password: baynazarow2971
  cache:
    cache-names: exchangeRate
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.crudshop.demo: INFO
    org.springframework.cache: TRACE

app:
  scheduling:
    period: 30000
    priceIncreasePercentage: 10

addressservice:
  base:
    url: http://localhost:8083/my-app

interaction:
  rate:
    stub: false
